[package]
name = "chatroom-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
